import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Header from "@/components/Header"
import Footer from "@/components/Footer"
import { APIProvider } from "@/contexts/APIContext"
import { FilterProvider } from "@/contexts/FilterContext"
import { UserProvider } from "@/contexts/UserContext"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <APIProvider>
      <FilterProvider>
      <UserProvider>
          <body className={inter.className}>
            <Header/>

            {children}

            <Footer/>
          </body>
      </UserProvider>
      </FilterProvider>
      </APIProvider>
    </html>
  );
}
